### ISSUE TITLE
enable dependabot for this repo

### ISSUE THREAD

**Issue by mblumenstingl-n11** [codecentric-oss/http-api-proxy-server#5]
There's a critical security vulnerability for `axios`: https://github.com/axios/axios/releases/tag/v1.6.0
It would be nice if the `http-api-proxy-server` would come with an up-to-date axios version and it's verified that all tests are passing against the newer axios version.

**Comment by RichardSiegel** [comment]
0.0.11 will include this and other security updates. Also dependabot is enabled from now on.
Unit tests will still be improved.
The Playwight tests we have should ensure everything keeps running.
